dist: trusty
sudo: required
language: go
go:
- "1.11"
before_script:
- go get github.com/kardianos/govendor
script:
- make build
- make test
- make vendor-status
- make vet
branches:
  only:
  - master
  - ci
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

